pipeline {
    agent any 
    tools { 
        maven 'Maven' 
        jdk 'Java' 
    }
    stages {
        stage('Clone git and clean') { 
            steps {
                dir("${env.WORKSPACE}/SampleJenkinsMaven"){
                    bat "mvn clean"
                }
                    
            }
        }
        stage('Test') { 
            steps {
                dir("${env.WORKSPACE}/SampleJenkinsMaven"){
                    bat "mvn test"
                }
            }
        }
        stage('Deploy') { 
            steps {
               dir("${env.WORKSPACE}/SampleJenkinsMaven"){
                    bat "mvn package"
                }
            }
        }
        
    }
}